# Generated by Django 2.1.3 on 2019-01-30 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminio'), ('O', 'Outro')], max_length=1)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lavanderia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=30)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lavanderia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico_pedido', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('A', 'Aguardando'), ('C', 'Confirmada')], max_length=1)),
                ('qtd_roupas', models.IntegerField()),
                ('observacoes', models.CharField(max_length=255)),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='washes.Consumidor')),
                ('lavanderia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='washes.Lavanderia')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico_solicitado', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('A', 'Aguardando'), ('C', 'Confirmada')], max_length=1)),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='washes.Consumidor')),
                ('lavanderia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='washes.Lavanderia')),
            ],
        ),
    ]
