# Generated by Django 2.1.5 on 2019-02-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('A', 'Aguardando'), ('C', 'Confirmada')], default='A', max_length=1),
        ),
    ]
