# Generated by Django 2.1.5 on 2019-02-06 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('washes', '0002_auto_20190205_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('A', 'Aguardando'), ('C', 'Confirmada'), ('R', 'Recusada')], default='A', max_length=1),
        ),
    ]
