# Generated by Django 2.1.5 on 2019-02-06 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('washes', '0003_auto_20190205_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacao',
            old_name='data_solicitacao',
            new_name='criado_em',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='data_solicitada',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
